{"name": "test_positive_create_user", "status": "failed", "statusDetails": {"message": "AssertionError: It isn't possible to create a user\nassert False", "trace": "setup_new_customer_screen = {'fe': <ProjectSeleniumPython.Pages.ExcelFunctions.Funexcel object at 0x00000164F4F9BFE0>, 'functions': <ProjectSeleni...eUsr object at 0x00000164F4E0D880>, 'path_excel': 'D://Projects//Projects//ProjectSeleniumPython//User_Data.xlsx', ...}\n\n    @pytest.mark.positive\n    @pytest.mark.usefixtures(\"log_on_failure\")\n    def test_positive_create_user(setup_new_customer_screen):\n        ctx = setup_new_customer_screen\n        newCustomer = ctx[\"newCustomer\"]\n        fe = ctx[\"fe\"]\n        path_excel = ctx[\"path_excel\"]\n        f = ctx[\"functions\"]\n        try:\n            newCustomer.EnterFirstName(fe.readData(path_excel, \"magento_new_users\", 3, 2))\n            newCustomer.EnterLastName(fe.readData(path_excel, \"magento_new_users\", 3, 3))\n            newCustomer.EnterEmail(fe.readData(path_excel, \"magento_new_users\", 3, 4))\n            newCustomer.EnterPassw(fe.readData(path_excel, \"magento_new_users\", 3, 5))\n            newCustomer.ConfirmPassw(fe.readData(path_excel, \"magento_new_users\", 3, 6))\n            newCustomer.PressButtonCreate()\n    \n            # text = f.Sel_by_Xpath(\"//span[@class='base'][contains(.,'My Account')]\", t).text\n>           text = f.return_element(\"xpath\", \"//span[@class='base'][contains(.,'My Account')]\", t).text\nE           AttributeError: 'NoneType' object has no attribute 'text'\n\nTests\\test_CreateUser.py:94: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nsetup_new_customer_screen = {'fe': <ProjectSeleniumPython.Pages.ExcelFunctions.Funexcel object at 0x00000164F4F9BFE0>, 'functions': <ProjectSeleni...eUsr object at 0x00000164F4E0D880>, 'path_excel': 'D://Projects//Projects//ProjectSeleniumPython//User_Data.xlsx', ...}\n\n    @pytest.mark.positive\n    @pytest.mark.usefixtures(\"log_on_failure\")\n    def test_positive_create_user(setup_new_customer_screen):\n        ctx = setup_new_customer_screen\n        newCustomer = ctx[\"newCustomer\"]\n        fe = ctx[\"fe\"]\n        path_excel = ctx[\"path_excel\"]\n        f = ctx[\"functions\"]\n        try:\n            newCustomer.EnterFirstName(fe.readData(path_excel, \"magento_new_users\", 3, 2))\n            newCustomer.EnterLastName(fe.readData(path_excel, \"magento_new_users\", 3, 3))\n            newCustomer.EnterEmail(fe.readData(path_excel, \"magento_new_users\", 3, 4))\n            newCustomer.EnterPassw(fe.readData(path_excel, \"magento_new_users\", 3, 5))\n            newCustomer.ConfirmPassw(fe.readData(path_excel, \"magento_new_users\", 3, 6))\n            newCustomer.PressButtonCreate()\n    \n            # text = f.Sel_by_Xpath(\"//span[@class='base'][contains(.,'My Account')]\", t).text\n            text = f.return_element(\"xpath\", \"//span[@class='base'][contains(.,'My Account')]\", t).text\n    \n            allure.attach(f.driver.get_screenshot_as_png(), name=\"CreatingUser\", attachment_type=AttachmentType.PNG)\n    \n        except AttributeError as ex:\n            fe.writeData(path_excel, \"magento_new_users\", 3, 7, \"Failed - It isn't possible to create a user\")\n>           assert False, \"It isn't possible to create a user\"\nE           AssertionError: It isn't possible to create a user\nE           assert False\n\nTests\\test_CreateUser.py:100: AssertionError"}, "start": 1747879520382, "stop": 1747879533845, "uuid": "e3276d1c-df61-4f24-9693-3351ba17112b", "historyId": "2c952d1e82745571f01b4a5b1b218662", "testCaseId": "2c952d1e82745571f01b4a5b1b218662", "fullName": "Tests.test_CreateUser#test_positive_create_user", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('log_on_failure')"}, {"name": "tag", "value": "positive"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_CreateUser"}, {"name": "host", "value": "JHOHAN-LapTop"}, {"name": "thread", "value": "25368-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_CreateUser"}]}